---

- name: retrieves and launches 'docker swarm' image
  docker: 
    image: library/swarm:latest
    hostname: '{{ ansible_hostname }}'
    name: docker-swarm
    command: 'join --addr={{ ansible_eth0.ipv4.address }}:2376 token://{{ docker_swarm_token }}'
    restart_policy: always # try to restart if the container exists
    restart_policy_retry: 3 # it will try to restart 3 times before giving up
    state: started