# See: https://docs.docker.com/swarm/
# See: https://docs.docker.com/swarm/install-manual/
# See: https://registry.hub.docker.com/_/swarm/

- include: client.yml
  tags:
    - docker-swarm


- include: manager.yml
  when: docker_swarm.manager == ansible_eth0.ipv4.address # if manager host
  tags:
    - docker-swarm