# Common roles for all hosts

- name: sets hostname
  hostname: 
    name: "{{ hostname }}"
  tags:
    - common


- name: configures apt sources
  template: 
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
  tags:
    - common


- name: "updates apt cache & upgrades dist"
  apt: 
    upgrade: "yes"
    update_cache: yes
  tags:
    - common


- name: installs the necessary software
  apt: 
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - sudo
    - zsh # for oh-my-zsh support
    - htop
    - mc
    - git
    - screen
    - lshw
    - python-pip  # Require for 'pip' ansible module
  tags:
    - common