- name: fix permissions
  file:
    path: "/home/{{ item.user }}/"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ ssh.users }}"
  when: ssh.users is defined